### ISSUE TITLE
Nightly builds link broken

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#28]
The nightly builds link is broken. 

[

https://github.com/user-attachments/assets/edd14bb8-250a-4a5e-b25b-8812e45a7d9d

](url)

Also while I'm talking about nightly builds, any idea when the next version of Appleblox will be released?

**Comment by OrigamingWasTaken** [comment]
Yes those are broken due to the switch to the the AppleBlox organization, they're fixed in the dev branch but maybe I will manually fix them from GitHub. Also for the next version, I currently need 2 things to release it as the new stable version:
- An Apple developer account, to codesign the application
- More testing to catch potential bugs

If you haven't already, you can test the new 0.8.0 version from the "dev" branch.

**Comment by bdc0der** [comment]
Alright good to know, thanks.

**Comment by OrigamingWasTaken** [comment]
You can download it using, well the nightly link for the dev branch: https://nightly.link/AppleBlox/appleblox/workflows/build/dev?preview

**Comment by bdc0der** [comment]
https://github.com/user-attachments/assets/58c7b494-51f1-4937-90fd-51d8e2428a20

Maybe I'm doing something wrong or the link is broken, idk. But the link you gave me works, thanks.
